name: mobile_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.0.6
  provider: ^6.0.3
  http: ^0.13.3
  cached_network_image: ^3.2.1
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8
  shared_preferences: ^2.0.6
  google_maps_webservice: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
